### ISSUE TITLE
Open dictionary fails on \" which is the double stress marker

### ISSUE THREAD

**Issue by rohrlich** [emer/auditory#5]
Using reduced dictionary until resolved

**Comment by rcoreilly** [comment]
can you just do a replace of \" in your file to something else to mark double-stress?

**Comment by rohrlich** [comment]
Yes absolutely can do that, as long as I document for anyone wanting to use the code so they can do the same replace on a dictionary of their own.

**Comment by rohrlich** [comment]
~ replaced \" in the dictionary - In fact the original dictionary just had " but that was converted in our code to \" to escape the ".
- the new dictionary is named VocalTractEnglishDict2.dat
